name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build the PDF
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          ASIR/1/planificacion_administracion_redes/redes_book.pdf
          ASIR/2/SGBD/sgbd_book.pdf
          DAM/1/sistemas_informaticos/sistemas_informaticos.pdf
          DAM/1/sistemas_informaticos/sistemas_informaticos_web.pdf
          DAM/2/desarrollo_interfaces/desarrollo_interfaces.pdf
          DAM/2/sistemas_gestion_empresarial/sistemas_gestion_empresarial.pdf
          SMR/2/SOred/SOred.pdf
          otros/Docker/docker_book.pdf
          otros/git/git_book.pdf
          otros/hacer_documentacion/como_hacer_documentacion.pdf
          otros/PFsense/pfsense_book.pdf
          temas_comunes/laravel/laravel_book.pdf
          anexos/gestion_backups/gestion_backups_anexo.pdf
          anexos/glosario/glosario_anexo.pdf
          anexos/instalar_ubuntu_lts/instalar_ubuntu_lts_anexo.pdf
          anexos/monitorizacion_munin/monitorizacion_munin_anexo.pdf
          anexos/sistemas_monitorizacion/sistemas_monitorizacion_anexo.pdf
          anexos/tabla_sistemas_numeracion/tabla_sistemas_numeracion_anexo.pdf
          anexos/ubuntu_raid1/ubuntu_raid1_anexo.pdf
          anexos/virtualbox_networking/virtualbox_networking_anexo.pdf
