name: Build PDF
on:
  workflow_dispatch:
    inputs:
      libro:
        description: 'Libro a compilar'
        required: true
        default: 'SOred'
        type: choice
        options:
        - SOred
        - Redes
        - SGBD
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: build the PDF
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build.sh ${{ github.event.inputs.libro}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.inputs.libro}}.pdf
