name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build the PDF
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files:
          SMR/2ยบ/Sistemas operativos en red/SOred.pdf
          ASIR/2ยบ/SGBD/sgbd_book.pdf
          otros/PFsense/pfsense_book.pdf
