name: Pandoc Books Build
on: 
  workflow_dispatch:
    inputs:
      compileBook:
        description: 'Which Book compile?'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - ASO
          - AWS
          - AWS_docentes
          - Como_hacer_documentacion
          - Desarrollo_Interfaces
          - Docker
          - Gestion_backups
          - Git
          - Glosario
          - Instalar_Ubuntu_LTS
          - Laravel
          - Monitorizacion_Munin
          - PFsense
          - Redes
          - SGBD
          - SGE
          - Sistemas_Informaticos
          - Sistemas_Monitorizacion
          - Ubuntu_RAID1
          - Virtualbox_networking
          - WSL
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build the PDF and HTML
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build_pandoc.sh
      env:
        COMPILEBOOK: ${{inputs.compileBook}}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: |
          otros/aws/aws.pdf
          otros/aws_docentes/aws_docentes.pdf
          otros/Docker/docker.pdf
          otros/git/git.pdf
          otros/hacer_documentacion/como_hacer_documentacion.pdf
          otros/laravel/laravel.pdf
          otros/PFsense/pfsense.pdf
          ASIR/1/planificacion_administracion_redes/redes.pdf
          ASIR/2/administracion_sistemas_operativos/aso.pdf
          ASIR/2/SGBD/sgbd.pdf
          DAM/1/sistemas_informaticos/si.pdf
          DAM/2/desarrollo_interfaces/desarrollo_interfaces.pdf
          DAM/2/sistemas_gestion_empresarial/sge.pdf
          anexos/gestion_backups/gestion_backups.pdf
          anexos/glosario/glosario.pdf
          anexos/instalar_ubuntu_lts/instalar_ubuntu_lts.pdf
          anexos/monitorizacion_munin/monitorizacion_munin.pdf
          anexos/sistemas_monitorizacion/sistemas_monitorizacion.pdf
          anexos/ubuntu_raid1/ubuntu_raid1.pdf
          anexos/virtualbox_networking/virtualbox_networking.pdf
          temas_comunes/wsl/wsl.pdf
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
