name: Pandoc Books Build
on: 
  workflow_dispatch:
    inputs:
      compileBook:
        description: 'Which Book compile?'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - AWS
          - Como_hacer_documentacion
          - Docker
          - Git
          - Laravel
          - PFsense
          - ASO
          - SGBD
          - SI
          - SGE
          - Desarrollo_Interfaces
          - Gestion_backups
          - Instalar_Ubuntu_LTS
          - Monitorizacion_Munin
          - Ubuntu_RAID1
          - Sistemas_Monitorizacion
          - Virtualbox_networking
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build the PDF and HTML
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build_pandoc.sh
      env:
        COMPILEBOOK: ${{inputs.compileBook}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          otros/aws/aws_book.pdf
          otros/Docker/docker_book.pdf
          otros/git/git_book.pdf
          otros/hacer_documentacion/como_hacer_documentacion_book.pdf
          otros/laravel/laravel_book.pdf
          otros/PFsense/pfsense_book.pdf
          ASIR/2/administracion_sistemas_operativos/aso_book.pdf
          ASIR/2/SGBD/sgbd_book.pdf
          DAM/1/sistemas_informaticos/si_book.pdf
          DAM/2/desarrollo_interfaces/desarrollo_interfaces_book.pdf
          DAM/2/sistemas_gestion_empresarial/sge_book.pdf
          anexos/gestion_backups/gestion_backups_anexo.pdf
          anexos/instalar_ubuntu_lts/instalar_ubuntu_lts_anexo.pdf
          anexos/monitorizacion_munin/monitorizacion_munin_anexo.pdf
          anexos/sistemas_monitorizacion/sistemas_monitorizacion_anexo.pdf
          anexos/ubuntu_raid1/ubuntu_raid1_anexo.pdf
          anexos/virtualbox_networking/virtualbox_networking_anexo.pdf
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: './build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
